name    'jeffmccune-puppet'
version '0.0.2'
source 'UNKNOWN'
author 'jeffmccune'
license 'Apache'
summary 'Puppet Labs Master of Masters Module'
description 'This module manages Puppet itself in the Master of Masters implementation.'
project_page 'https://github.com/puppetlabs/jeffmccune-puppet'

## Add dependencies, if any:
dependency 'jeffmccune/apache', '>= 0.0.1'

