#! /usr/bin/env ruby
#

require 'puppet'
require 'trollop'
require 'fileutils'

@opts = Trollop::options do
  banner <<-ENDOFSTRING
This small script populates SSL information for the load balancer.  It copies
certificate data from the seed puppet master and is expected to place these in
the templates directory.

A certificate and private key should be generated for the Load Balancer prior
to running this command.

    puppet cert --generate puppet --certdnsnames puppet.puppetlabs.vm:puppet

The output is designed to be piped into a bash -x

For example, #{$0} --confdir /etc/puppet_prod | bash -x
ENDOFSTRING
  opt :confdir, "Puppet confdir setting", :type => String
  opt :certname, "SSL Certificate Common Name", :default => "puppet"
end

Puppet.settings[:confdir] = @opts[:confdir]
Puppet.parse_config

ssldir = Puppet.settings[:ssldir]
certname = @opts[:certname]

# CA Cert ssl_ca_cert
puts "cp '#{File.join(ssldir, "ca", "ca_crt.pem")}' ssl_ca_cert"
# SSL Cert Chain (Should match CA Cert) ssl_cert_chain
puts "cp '#{File.join(ssldir, "ca", "ca_crt.pem")}' ssl_cert_chain"
# CA CRL ssl_ca_crl
puts "cp '#{File.join(ssldir, "ca", "ca_crl.pem")}' ssl_ca_crl"
# SSL Cert ssl_cert
puts "cp '#{File.join(ssldir, "certs", "#{certname}.pem")}' ssl_cert"
# SSL Cert Key ssl_cert_key
puts "cp '#{File.join(ssldir, "private_keys", "#{certname}.pem")}' ssl_cert_key"

puts "# Finished!"
